### ISSUE TITLE
A panic ramdomly occurs in the APIs, probably caused by the scheduler and actions on events

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#506]
There is a panic that occurs "randomly" in the APIs, which I have been unable to reproduce manually. It is probably caused by the scheduler in presence of actions on events.

If I recall correctly, it happened here:

https://github.com/open2b/chichi/blob/c62853c66a42871fa68dc4642a50c166eb18c171/apis/exec_import.go#L74

We need to investigate this and determine what conditions cause the panic in order to reproduce it and understand the issue.

**Comment by zapateo** [comment]
## Stack trace

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c6b2fe]

goroutine 101862 [running]:
chichi/apis.(*Action).importUsers(0xc0009a0640, {0x2c5a758, 0xc000aaf220})
        chichi/apis/exec_import.go:78 +0x89e
chichi/apis.(*Action).exec(0xc0009a0640, {0x2c5a758, 0xc000aaf220})
        chichi/apis/exec.go:94 +0x115
chichi/apis.(*APIs).onExecuteAction.func1()
        chichi/apis/apis.go:692 +0x5b
created by chichi/apis.(*APIs).onExecuteAction in goroutine 53
        chichi/apis/apis.go:690 +0x19c
```

## Connections

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/22b4e735-7d0e-41f1-83f1-9474b5dbda9b)

## Actions

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/3a193c2d-f853-48d6-975e-973024a1788b)
